config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: absolute
  link_on_import: absolute
  longkey: false
  key_prefix: false
actions:
  pre:
    packer-install: test -e ~/.local/share/nvim/site/pack/packer/start/packer.nvim || git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
  packer: nvim +PackerSync +qall
dotfiles:
  nvim:
    dst: ~/.config/nvim
    src: nvim
    actions:
      - packer-install
      - packer
  gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  gitignore:
    src: gitignore
    dst: ~/.gitignore
  fish:
    src: fish
    dst: ~/.config/fish
profiles:
  jorens-macbook.local:
    dotfiles:
    - nvim
    - gitconfig
    - gitignore
    - fish
    variables:
      git_email: 231202+jorenvanhee@users.noreply.github.com
  jorens-macbook-work.local:
    dotfiles:
    - nvim
    - gitconfig
    - gitignore
    variables:
      git_email: joren.vanhee@catsolutions.be
